### ISSUE TITLE
Cant decode some messages

### ISSUE THREAD

**Issue by aikihook** [KimBP/AIS#10]
Hi
This looks like a great library that will save me time with my project. I have implemented the Arduino example code exactly. But in my testing quite a few strings I get no sensible information ( yet they decode using online tools ok).

This works:
> !AIVDM,1,1,,B,13P<Kt0P00wrp8pM4kLUt?wp0@1a,0*4E

[portico_ais.txt](https://github.com/KimBP/AIS/files/5550236/portico_ais.txt)

These don't (just two out of a few hundred that I have captured)

> !AIVDM,1,1,,A,402MN7ivBmfRWwrrk8M4Eb?028GV,0*19

and multiple message, how do you handle multiple fragment ?
> !AIVDM,2,1,6,B,53MAOlD2E?E8lHIc>20l58e<l4r222222222220l1p?556gP0=T3lU4k,0*75
> !AIVDM,2,2,6,B,CmE288888888880,2*78

I have been constructing using AIS ais_msg("with payload field 6")

Thanks

**Comment by KimBP** [comment]
This is strange. I've just been running all your 3 examples with the vdm_dump sample program you find in Examples/linux.

Output can bee seen here:
```
$ ./vdm_dump -
Expecting stdin
!AIVDM,1,1,,B,13P<Kt0P00wrp8pM4kLUt?wp0@1a,0*4E
1 of 1: 13P<Kt0P00wrp8pM4kLUt?wp0@1a
1 (PosReport): mmsi=235084784 SOG=0
!AIVDM,1,1,,B,13P<Kt0P00wrp8pM4kLUt?wp0@1a,0*4E
1 of 1: 13P<Kt0P00wrp8pM4kLUt?wp0@1a
1 (PosReport): mmsi=235084784 SOG=0
!AIVDM,1,1,,A,402MN7ivBmfRWwrrk8M4Eb?028GV,0*19
1 of 1: 402MN7ivBmfRWwrrk8M4Eb?028GV
4 (StationReport): mmsi=2579999
!AIVDM,2,1,6,B,53MAOlD2E?E8lHIc>20l58e<l4r222222222220l1p?556gP0=T3lU4k,075
1 of 2: 53MAOlD2E?E8lHIc>20l58e<l4r222222222220l1p?556gP0=T3lU4k
!AIVDM,2,2,6,B,CmE288888888880,278
2 of 2: CmE288888888880
5 (StaticAndVoyage)): mmsi=232021969 name=MARKSMAN             

```

To answer the question on multi strings you can have a look from line 205 in vdm_dump.cpp:
In here you see how the first part of the xxVDM message has been analyzed to tell whether it is

1. a complete message (1 of 1) 
2. a first message of a multiple (1 of n), 
3. a none first and none last of a multiple message (m of n) (m != n and m != 1)
4. a last of a multiple message (n of n)

Nmb 1 hands over the encoded part to a function called handle_ais()
Nmb 2 copies the encoded part into a buffer
Nmb 3 appends the encoded part to the buffer
Nmb 4 appends the encoded part to the buffer and hands over the buffer to the handle_ais() function

The handle_ais() function basically creates an AIS object with the given data and extract data from it based on the type of AIS message.

I think you'll have to show some of your code if you want me to help any further

**Comment by aikihook** [comment]
I am simply using your AIS.h, AIS.cpp example Arduino AISDecode.ino, running on MKRFOX1200 SAMD board. Passing in the "payload" through serial input. This constructs AIS("message") and then calls showDecodedAIS() to print it out.

```
void loop()
{
   if (Serial.available() > 0)
  {
     // read the incoming command
     incoming = Serial.readString();
     // say what you got:
     Serial.println(incoming);
   
     AIS ais_msg(incoming.c_str());
     showDecodedAIS(ais_msg);
   }
}
```

```
void showDecodedAIS(AIS ais_msg) {
   showMsgType(ais_msg);
   showMMSI(ais_msg);
   showNavStatus(ais_msg);
   showSOG(ais_msg);
   showCOG(ais_msg);
   showLatitude(ais_msg);
   showLongitude(ais_msg);
}
```

Hmmh!! It now seems ok for what I want regarding Message Types: 1, 2 and 3.

But for StationReport 4, "402MN7ivBmfRWwrrk8M4Eb?028GV" - I was still expecting to see decoded output for **latitude** and **longitude** since these are parameters in msg type 4 specification @ 79-106 and 107-133

For messages type 5, I think I can figure it out now - thanks

**Comment by KimBP** [comment]
Sorry, I haven't looked at the library for a long time.
It seems like msg type 4 isn't really supported. See line 111..113 in AIS.cpp and compare to surrounding objects.
The reason for my test above not showing that type 4 isn't supported is that get_mmsi() is hardcoded to always request bit 8..37 (AIS.h line 57: uint32_t get_mmsi() { return get_u32(8,30); }; )

I can't remember why it was never implemented - maybe I didn't receive any messages of this type while testing with live data.


With these changes:


```
diff --git a/AIS.cpp b/AIS.cpp
index 576733b..6d3a4d5 100644
--- a/AIS.cpp
+++ b/AIS.cpp
@@ -109,6 +109,8
 @@ const struct AIS::AisParamPosPair AIS::AisMsgPosReportClassA[] = {
 };
 
 const struct AIS::AisParamPosPair AIS::AisMsgBaseStationReport[] = {
+               { AIS_PARAM_I32_LONG,      79 },
+               { AIS_PARAM_I32_LAT,      107 },
                { AIS_PARAM_MAX, 0 } // Must be last
 };
 
diff --git a/Examples/linux/vdm_dump.cpp b/Examples/linux/vdm_dump.cpp
index f9e664e..7c11872 100644
--- a/Examples/linux/vdm_dump.cpp
+++ b/Examples/linux/vdm_dump.cpp
@@ -88,6 +88,8 @@ void printBaseStationReport(AIS& ais)
 {
   printf("%d (StationReport): ", ais.get_numeric_type());
   printf("mmsi=%d", ais.get_mmsi());
+  printf(" lat=%d", ais.get_latitude());
+  printf(" long=%d", ais.get_longitude());
   printf("\n");
 }
 
@@ -95,7 +97,7 @@ void printStaticAndVoyage(AIS& ais)
 {
   printf("%d (StaticAndVoyage)): ", ais.get_numeric_type());
   printf("mmsi=%d ", ais.get_mmsi());
-  printf("name=%s ", ais.get_shipname());
+  printf(" name=%s ", ais.get_shipname());
   printf("\n");
 }
```
I get
```
$ ./vdm_dump -
Expecting stdin
!AIVDM,1,1,,A,402MN7ivBmfRWwrrk8M4Eb?028GV,0*19
1 of 1: 402MN7ivBmfRWwrrk8M4Eb?028GV
4 (StationReport): mmsi=2579999 lat=30479784 long=-666012
```

I haven't checked if the values are correct.

Feel free to upstream a patch implementing full support for message type 4.

**Comment by aikihook** [comment]
Hi Kim
I thought was simply missing the bit position for lat/lon from the StationReport. Actually my project is constrained to getting mmsi, lat/lon, name etc to count ships entering/leaving/waiting port authority geographic zones.

Thanks, this is a great library you have created and you have saved me a lot of effort. I continue my testing through the captured data I collected.

I will in due course expand and improve the messages i.e. full support for 4 .. and anything else I find that may be a benefit.

Many thanks

Jamie
