### ISSUE TITLE
Allocates strings based on msgType

### ISSUE THREAD

**Issue by usauerbrey** [KimBP/AIS#5]
Hi Kim

In AIS.h it is mentioned:
	//TODO: Allocates strings based on msgType
	char shipname[shipname_strlen + 1];
	char destination[destination_strlen+1];
	char callsign[callsign_strlen+1];
	char vendorid[vendorid_strlen+1];

Have you done something on this in the meantime? I would like to get these strings ;-)

best regards Uwe

**Comment by KimBP** [comment]
No - what you can access is my newest code. I think my TODO was to remind me of a possibility to save some memory as not all messages needs all strings. Maybe the way to implement it is to make inherited, message specific classes or do you have a better idea?
Feel free to come with a solution. I'll be happy to review it.

**Comment by usauerbrey** [comment]
Hi Kim
Do I understand you correctly, it just should work and the reminder was just to have a more efficient solution?
Currently I cannot access the strings succesfully, but this might be due to my very limited C++ knowledge. And in the decode examle there is sorrily no access to these strings.
Do you have a hint for me, how to access the ship name?

Thanks Uwe

**Comment by KimBP** [comment]
Hi Uwe 
I'm quite sure it will work even though I haven't really looked into it for a while. If you look in AIS.h you see the following 4 methods:
        const char* get_shipname() { return get_string(AIS_PARAM_T_SHIPNAME, shipname);};
        const char* get_destination() { return get_string(AIS_PARAM_T_DESTINATION, destination);};
        const char* get_callsign() { return get_string(AIS_PARAM_T_CALLSIGN, callsign);};
        const char* get_vendorid() { return get_string(AIS_PARAM_T_VENDORID, vendorid);};

They are basically 'inline' functions calling get_string() to extract the parameter in question into the 'internally' and hidden string member and afterwards returning a pointer to the string.

So yes my TODO is just an optimization reminder

Hope this helps you

**Comment by usauerbrey** [comment]
ok, I will try to find my bugs ;-)
Uwe
