### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by gzahl** [KimBP/AIS#8]
Hi,
Thanks for the code. What is the license? Can i reuse it, e.g. modify, incorporate into another Open Source library?
Thanks!

**Comment by KimBP** [comment]
Hi gzahl.

I've added a MIT license file as well as added a copyright/license header to all source files.
Hope it is not too restrictive for your purpose.

Feel free to report any bugs and of course you are also welcome to contribute with suggestions/improvements

**Comment by gzahl** [comment]
Thanks a lot. I will see if that fits and if i can use your code, when i can get back to it.
